"""Adding tag column to Page

Revision ID: 7421b5c33fff
Revises: 91ec9de0a192
Create Date: 2020-05-12 21:46:06.025102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7421b5c33fff'
down_revision = '91ec9de0a192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'tag')
    # ### end Alembic commands ###
